// <auto-generated />
namespace SpfInventaire.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nom_Materiel_Plus_Obligatoire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nom_Materiel_Plus_Obligatoire));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011505529_Nom_Materiel_Plus_Obligatoire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
