// <auto-generated />
namespace SpfInventaire.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajout_TypeMateriel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajout_TypeMateriel));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011423183_Ajout_TypeMateriel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
