// <auto-generated />
namespace SpfInventaire.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ticket_NumeroFeb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ticket_NumeroFeb));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231451089_Ticket_NumeroFeb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
