// <auto-generated />
namespace SpfInventaire.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gestion_Stock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gestion_Stock));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181224031_Gestion_Stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
